In [1]:
import import_ipynb
from Judd_Ofeld_Base import CarnalDataPrepare
import pandas as pd
from pathlib import Path

In [2]:
Carnal_U_data = pd.read_csv('./Carnal_data/Nd.txt',delimiter='\t')

In [3]:
Carnal_U_data.head(3)

   TERM1  TERM2  (U2)*2  (U4)*2  (U6)*2   LEVEL1   LEVEL2
0  2P1/2  4F3/2  0.0131     0.0     0.0  23458.0  11621.0
1  2P1/2  4S3/2  0.0175     0.0     0.0  23458.0  13691.0
2  2P1/2  2D3/2  0.0291     0.0     0.0  23458.0  21425.0

In [4]:
CDP = CarnalDataPrepare(init_U_data=Carnal_U_data)

In [5]:
CDP.prepared_data.head(3)

,TERM_i,TERM_f,U2,U4,U6,LEVEL1,LEVEL2,Energy,J_i,J_f,Term,Lambda
0,2P1/2,4F3/2,0.0131,0.0,0.0,23458.0,11621.0,11837.0,0.5,1.5,2P1/2-4F3/2,844.808651
1,2P1/2,4S3/2,0.0175,0.0,0.0,23458.0,13691.0,9767.0,0.5,1.5,2P1/2-4S3/2,1023.855841
2,2P1/2,2D3/2,0.0291,0.0,0.0,23458.0,21425.0,2033.0,0.5,1.5,2P1/2-2D3/2,4918.839154

### Save GroundData

In [6]:
ground_Er_U = CDP.ground

In [7]:
ground_Er_U.head(3)

,TERM_i,TERM_f,Term,Energy,U2,U4,U6,Lambda,J_i,J_f
0,2P3/2,4I9/2,2P3/2-4I9/2,26189.0,0.0,0.0010,0.0005,381.839704,1.5,4.5
1,2D5/2,4I9/2,2D5/2-4I9/2,23769.0,0.0,0.0002,0.0017,420.716059,2.5,4.5
2,2P1/2,4I9/2,2P1/2-4I9/2,23223.0,0.0,0.0396,0.0000,430.607587,0.5,4.5

In [8]:
ground_Er_U.to_csv(f'./U_data/Nd_Carnal_Ground.txt')

### Save LowerData with the addition of Amd Data information from another article.

In [9]:
lower_Er_U = CDP.lower
lower_Er_U.head(3)

  TERM_i TERM_f         Term   Energy      U2   U4   U6       Lambda  J_i  J_f
0  2P1/2  4F3/2  2P1/2-4F3/2  11837.0  0.0131  0.0  0.0   844.808651  0.5  1.5
1  2P1/2  4S3/2  2P1/2-4S3/2   9767.0  0.0175  0.0  0.0  1023.855841  0.5  1.5
2  2P1/2  2D3/2  2P1/2-2D3/2   2033.0  0.0291  0.0  0.0  4918.839154  0.5  1.5

In [10]:
def term_concat(df):
    return df.TERM1+'-'+df.TERM2

In [11]:
## Er A_MD (Probabilities for Radiative and Nonradiative Decay of Er'+ in LaF, Weber 1967)
df_Er_md = pd.read_csv('./Carnal_data/Nd_AMD_pre_n_2.16.txt',delimiter='\t')
df_Er_md['Term'] = df_Er_md.apply(lambda x:term_concat(x),axis=1)
df_Er_md['A_md_pre'] = df_Er_md.AMD_pre.apply(lambda x:x/(2.16**3))
df_Er_md.head(3)

   TERM1   TERM2  AMD_pre          Term  A_md_pre
0  4F5/2   4F3/2      0.4   4F5/2-4F3/2  0.039692
1  2H9/2  4I11/2      5.7  2H9/2-4I11/2  0.565605
2  2H9/2   4I9/2     27.7   2H9/2-4I9/2  2.748644

In [12]:
lower_Er_U = lower_Er_U.merge(right = df_Er_md[['Term','A_md_pre']], how='left', on='Term')
lower_Er_U = lower_Er_U.fillna(0)

In [13]:
print(lower_Er_U.shape)
lower_Er_U.query('A_md_pre>0')

(112, 11)

,TERM_i,TERM_f,Term,Energy,U2,U4,U6,Lambda,J_i,J_f,A_md_pre
96,2H9/2,4I11/2,2H9/2-4I11/2,10654.0,0.0028,0.0004,0.0254,938.614605,4.5,5.5,0.565605

In [14]:
lower_Er_U.to_csv(f'./U_data/Nd_Carnal_Lower.txt')